name: Build and Test
on:
  push:
    branches:
      - master
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v2
      - name: setu JDK
        uses: actions/setup-java@v2
        with:
         java-version: "1.8"
         distribution: temurin
      - name: Test
        run: mvn test
      - name: Package
        run: mvn clean package
     
